### ISSUE TITLE
Can not find issuer for staging server

### ISSUE THREAD

**Issue by Tvde1** [natemcmaster/LettuceEncrypt#194]
**Describe the bug**

When setting `"UseStagingServer": true`, the following output is given when my server runs:

```
fail: LettuceEncrypt.Internal.AcmeCertificateLoader[0]
      Failed to automatically create a certificate for [url removed]
      Certes.AcmeException: Can not find issuer 'C=US,O=(STAGING) Internet Security Research Group,CN=(STAGING) Pretend Pear X1' for certificate 'C=US,O=(STAGING) Internet Security Research Group,CN=(STAGING) Bogus Broccoli X2'.
         at Certes.Pkcs.CertificateStore.GetIssuers(Byte[] der)
         at Certes.Pkcs.PfxBuilder.FindIssuers()
         at Certes.Pkcs.PfxBuilder.Build(String friendlyName, String password)
         at LettuceEncrypt.Internal.CertificateFactory.CompleteCertificateRequestAsync(IOrderContext order, CancellationToken cancellationToken)
         at LettuceEncrypt.Internal.CertificateFactory.CreateCertificateAsync(CancellationToken cancellationToken)
         at LettuceEncrypt.Internal.AcmeCertificateLoader.CreateCertificateAsync(String[] domainNames, CancellationToken cancellationToken)
fail: LettuceEncrypt.Internal.AcmeCertificateLoader[0]
      Failed to create certificate
      Certes.AcmeException: Can not find issuer 'C=US,O=(STAGING) Internet Security Research Group,CN=(STAGING) Pretend Pear X1' for certificate 'C=US,O=(STAGING) Internet Security Research Group,CN=(STAGING) Bogus Broccoli X2'.
         at Certes.Pkcs.CertificateStore.GetIssuers(Byte[] der)
         at Certes.Pkcs.PfxBuilder.FindIssuers()
         at Certes.Pkcs.PfxBuilder.Build(String friendlyName, String password)
         at LettuceEncrypt.Internal.CertificateFactory.CompleteCertificateRequestAsync(IOrderContext order, CancellationToken cancellationToken)
         at LettuceEncrypt.Internal.CertificateFactory.CreateCertificateAsync(CancellationToken cancellationToken)
         at LettuceEncrypt.Internal.AcmeCertificateLoader.CreateCertificateAsync(String[] domainNames, CancellationToken cancellationToken)
         at LettuceEncrypt.Internal.AcmeCertificateLoader.LoadCerts(CancellationToken cancellationToken)
         at LettuceEncrypt.Internal.AcmeCertificateLoader.<>c__DisplayClass15_0.<<ExecuteAsync>b__0>d.MoveNext()
Failed to automatically create a certificate for [url removed]
      Certes.AcmeException: Can not find issuer 'C=US,O=(STAGING) Internet Security Research Group,CN=(STAGING) Pretend Pear X1' for certificate 'C=US,O=(STAGING) Internet Security Research Group,CN=(STAGING) Bogus Broccoli X2'.
```

**To Reproduce**
1. Using this version of the library 'v1.0.1'
2. Run this code '....'
3. With these arguments '....'

**Expected behavior**

A staging cert will be generated

**Screenshots**

**Additional context**

**Comment by Tvde1** [comment]
Apparently this is due to the fact that Let's Encrypt is changing their staging keys, and my server does not have their CE trusted (see [https://letsencrypt.org/docs/staging-environment/#root-certificates](https://letsencrypt.org/docs/staging-environment/#root-certificates)).

I don't think this is something for this library to solve so feel free to close it if I am correct with this assumption.

**Comment by natemcmaster** [comment]
If I remember right, I think @huesie ran into this issue as well, and solved it by forking this project and adding automatic fetching of the staging server CA certs. If this is a general problem for others, I'd be interested in taking a contribution to make it easier to solve.

**Comment by MxFr** [comment]
The root cause for this problem lies in the fact that Certes does not include the new staging keys in [their set of embedded](https://github.com/fszlin/certes/tree/master/src/Certes/Resources/Certificates).

I've tried to install the staging certificates to the current users certificate store for testing but that did not work. So I would be thankful for some pointers on how to mitigate this issue.

**Comment by natemcmaster** [comment]
I've just merged https://github.com/natemcmaster/LettuceEncrypt/pull/279. Can you take a look at this and see if it solves your problem?

**Comment by Codeh4ck** [comment]
> I've just merged #279. Can you take a look at this and see if it solves your problem?

It doesn't solve the issue. With the latest version (1.2.0), I get the same problem on my own end here.

**Comment by FreeApophis** [comment]
You have to test against main, the NuGet is does not have the fix.

**Comment by natemcmaster** [comment]
You can also test with https://www.nuget.org/packages/LettuceEncrypt/1.3.0-beta.246

**Comment by netclectic** [comment]
I'm seeing the same issue with the current beta version: 1.3.0-beta.249

**Comment by natemcmaster** [comment]
@netclectic can you share the steps you are using so I can reproduce the problem?

**Comment by netclectic** [comment]
> @netclectic can you share the steps you are using so I can reproduce the problem?

I made a repo - https://github.com/netclectic/Blazor_LettuceEncrypt

Its using ngrok, so you will need to follow the integration test instructions and change the values in the appsettings.

https://github.com/natemcmaster/LettuceEncrypt/tree/main/test/Integration

**Comment by orkylish** [comment]
I'm also seeing this same issue with 1.3.0-beta.249

**Comment by natemcmaster** [comment]
Have you tried using the `AdditionalIssuers` option?

https://github.com/natemcmaster/LettuceEncrypt/blob/4dfcf037ba0ebde9109c7ba503be39c094bc5e0d/src/LettuceEncrypt/LettuceEncryptOptions.cs#L51-L65

**Comment by Mafii** [comment]
@orkylish @netclectic alternatively you can use `ICertificateAuthorityConfiguration`'s new property `IssuerCertificates`. Internally, it is passed into certes the same way the `AdditionalIssuers` are, as shown by nate. You will have to manually pass the staging root certificate (what certificate exactly can be learned here: https://letsencrypt.org/docs/staging-environment/). For example, just read the text and add it to the options (or the property). LettuceEncrypt does not automatically register a staging certificate when you set `UseStagingServer` to `true` - it has be done manually (unlike Certbot, when you pass `--test-cert`). 

Everything else should be clear if you read the xml documentation of `AdditionalIssuers` that nate included in his comment! I can also help if needed, you can just reply to me, here.
